[package]
name = "s3fs"
version = "0.1.0"
authors = ["Antonio Yang <antonio.yang@siliconmotion.com.tw>"]
edition = "2018"

[dependencies]
fuse = "^0.3.1"
colored = "^1.6.1"
time = "^0.1.42"
libc = "^0.2.48"
